### PR TITLE
feature: SOS 2.0.0

### PR DESCRIPTION
**Pull request by staschc**
* correct version of SOS 2.0.0
* ...

### CODE REVIEW

**Comment by CarstenHollmann** [comment]
The OGC SOS version is **2.0** ([OGC SOS interface standard](http://www.opengeospatial.org/standards/sos)).
The the value of the version query parameter is **2.0.0**.

**Comment by nuest** [comment]
@bpross-52n @staschc please discuss with Carsten the naming "2.0" vs. "2.0.0".

I suggest for internal class names we use the full one, but the parameter the user applies to set the version should only be `"2.0"` (which internal will be the same as `2.0.0`, but at a later stage might automatically be mapped to `2.0.x`.

**Comment by ridoo** [comment]
@nuest Internally class names also can have the "reduced" version as in OGC schema versioning `x.y.z.` the `z` indicates a schema fix. I think there is no need here to rename classes when a schema fix have to be applied.

**Comment by nuest** [comment]
The schema fix might require to handle encoding decoding differently, right? And that is only possible if there are different classes in the current model.

**Pull request merged**
